# 故障安全异常处理

> 原文：<https://jenkov.com/tutorials/java-exception-handling/fail-safe-exception-handling.html>

异常处理代码必须是故障安全的。要记住的一条重要规则是

```
The last exception thrown in a try-catch-finally block is
the exception that will be propagated up the call stack.
All earlier exceptions will disappear.

```

如果异常是从 catch 或 finally 块内部引发的，该异常可能会隐藏由该块捕获的异常。当试图确定错误的原因时，这是一种误导。

以下是非故障安全异常处理的典型示例:

```
  InputStream input = null;

  try{

    input = new FileInputStream("myFile.txt");

    //do something with the stream

  } catch(IOException e){
    throw new WrapperException(e);
  } finally {
    try{
     input.close();
    } catch(IOException e){
       throw new WrapperException(e);
    }
  }

```

如果 FileInputStream 构造函数抛出一个 FileNotFoundException，你认为会发生什么？

首先执行 catch 块。该块只是重新抛出包装在 WrapperException 中的异常。

其次，将执行关闭输入流的 finally 块。但是，由于 FileInputStream 构造函数引发了 FileNotFoundException，因此“input”引用将为 null。结果将是从 finally 块中抛出 NullPointerException。NullPointerException 没有被 finally 块的 catch(IOException e)子句捕获，因此它被向上传播到调用堆栈。从 catch 块抛出的 WrapperException 将会消失！

处理这种情况的正确方法当然是在调用任何方法之前检查在 try 块中分配的引用是否为空。这是它的样子:

```
  InputStream input = null;

  try{

    input = new FileInputStream("myFile.txt");

    //do something with the stream

  } catch(IOException e){ //first catch block
    throw new WrapperException(e);
  } finally {
    try{
     if(input != null) input.close();
    } catch(IOException e){  //second catch block
       throw new WrapperException(e);
    }
  }

```

但是即使是这种异常处理也有问题。让我们假设该文件存在，因此“input”引用现在指向一个有效的 FileInputStream。让我们假设在处理输入流时抛出了一个异常。该异常在 catch(IOException e)块中被捕获。然后，它被包裹并再次抛出。在包装的异常沿调用堆栈向上传播之前，执行 finally 子句。如果 input.close()调用失败，并且抛出 IOException，那么它将被捕获、包装并重新抛出。但是，当从 finally 子句中抛出包装异常时，从第一个 catch 块中抛出的包装异常再次被遗忘。它消失了。只有从第二个 catch 块引发的异常会沿调用堆栈向上传播。

正如您所看到的，故障安全异常处理并不总是微不足道的。InputStream 处理示例甚至不是您能遇到的最复杂的示例。JDBC 的交易有更多出错的可能性。当尝试提交，然后回滚，最后尝试关闭连接时，可能会出现异常。所有这些可能的异常都应该由异常处理代码来处理，所以它们都不会使第一个抛出的异常消失。一种方法是确保最后抛出的异常包含所有以前抛出的异常。这样，调查错误原因的开发人员就可以使用它们了。这就是我们的 Java 持久性 API Mr Persister 实现事务异常处理的方式。

顺便说一下，Java 7 中的 [try-with-resources](try-with-resources.html) 特性使得实现故障安全异常处理更加容易。